version: "3.8"

services:
  app:
    container_name: laravel-app
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./laravel-app:/var/www/html
    working_dir: /var/www/
    tty: true

  db:
    container_name: laravel-app-db
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-app-db
      TZ: Asia/Tokyo
    volumes:
      - ./my.ini:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql